#!/usr/bin/env bash
# This script transfers a file to a server

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

scp -i $SSH_KEY -o StrictHostKeyChecking=no $FILE $USERNAME@$SERVER_IP:~/
#checking if file transfer was succesful
if [ #? -qe 0]
then
    echo "FILE WAS TRANSFERRED SUCCESFULLY"
else
    echo "FILE TRANSFER FAILED"
