#!/usr/bin/env bash
# Script to start, stop, or restart the manage_my_process script and manage its PID

PIDFILE=/var/run/my_process.pid

case "$1" in
   start)
        ./manage_my_process &   # run the script in the background
        echo $! > ${PIDFILE}    # write PID to file
        echo "manage_my_process started"
        ;;
   stop)
        kill "$(cat ${PIDFILE})" # kill the process with the PID from file
        rm ${PIDFILE}   # remove the file
        echo "manage_my_process stopped"
        ;;
   restart)
        kill "$(cat ${PIDFILE})" # kill the process with the PID from file
        rm ${PIDFILE}   # remove the file
        ./manage_my_process &   # run the script in the background
        echo $! > ${PIDFILE}    # write PID to file
        echo "manage_my_process restarted"
        ;;
   *)
        echo "Usage: $0 {start|stop|restart}"
esac
