#!/usr/bin/env bash
#a Bash script that displays To infinity and beyond indefinitely With a sleep2

on_sigterm(){
	echo "I am invincible!!!"
}

trap "on_sigterm" SIGTERM

while true
do
		echo "To infinity and beyond"
		sleep 2
done
